@api=http://localhost:3000/api

###
post {{api}}/posts/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoieWlueTIiLCJpZCI6IjVkNjkwNzM2YjE4YzFhM2U4Y2MxZmMyOSIsImlhdCI6MTU2NzY2MzgyN30.DHkpb7ssc1wJTl81nrHaNXZusvlVLuwtQIoPzIN5azc

{
  "title": "Windows Core OS",
  "content": "传闻已久的Windows Core OS正在为“下一代”微软设备做准备，最新的微软软件工程师LinkedIn个人资料信息暗示如此。“经验丰富的C++开发人员，具有云管理操作系统开发方面的专业知识。在物联网设备，下一代WCOS设备，Windows桌面，HoloLens和Windows Server上提供基于Azure的设备管理功能和协议，”该工程师在简介中写道。"
}

### fetch all data
get {{api}}/posts/5d6cf1a404c0ba6be617b96f

### signup
post {{api}}/user/signup
Content-Type: application/json

{
  "username": "test",
  "password": "1"
}

### login
post {{api}}/user/login
Content-Type: application/json

{
  "username": "yiny2",
  "password": "1"
}

### get user info 
get {{api}}/user/5

### get posts list
get {{api}}/posts?&state=2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsInVzZXJuYW1lIjoidGVzdCIsImlkIjoiNWQ2Y2EwZGViNDJmZDcxN2M3ZmU5NjA0IiwiaWF0IjoxNTY3NDI1NzcyfQ.J5idUWC6WnSNjd5N5ChIUfY3LrCSLuGPJNC2tYaM9K4
